AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Deploy Test

Resources:
  CRUDItem:
    Type: AWS::Serverless::Function
    Properties:
      Handler: crud_item.lambda_handler
      Runtime: python3.8
      Timeout: 180
      CodeUri: crud-func